name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./redis/Dockerfile
        push: true
        tags: username/redis-cluster:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Dynatrace Monitoring
      run: |
        curl -X POST "https://<dynatrace-url>/api/config/v1/autoTags" \
        -H "Authorization: Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '@dynatrace/autoTag.json'
